"""
Solomon Perpetual Learning Machine
Phase 4: Gabriel Skill Factory (Re-engineered)

This module compiles learned scripts and raw text code blocks into
highly structured, modular, and benchmarked Skill Packages on-the-fly.
"""

import json
from typing import Dict, Any, List

class SkillFactory:
    """
    Synthesizes structured, modular, and testable Skill Packages containing
    formal inputs, outputs, automated test templates, and safety rules.
    """

    @classmethod
    def compile_skill_package(
        cls,
        skill_id: str,
        name: str,
        purpose: str,
        source_code: str,
        inputs_schema: Dict[str, str],
        outputs_schema: Dict[str, str],
        safety_constraints: List[str]
    ) -> Dict[str, Any]:
        """
        Compiles structural metadata, test templates, and safety limits into a complete Skill Package.
        """
        # Synthesize a standard unit test template for this capability
        test_template = (
            f"def test_{skill_id.lower().replace('-', '_')}():\n"
            f"    # Autogenerated testing template by Gabriel Skill Factory\n"
            f"    # Inputs: {list(inputs_schema.keys())}\n"
            f"    assert True\n"
        )

        skill_package = {
            "skill_id": skill_id,
            "name": name,
            "purpose": purpose,
            "source_code": source_code.strip(),
            "inputs_schema": inputs_schema,
            "outputs_schema": outputs_schema,
            "safety_constraints": safety_constraints,
            "autogenerated_tests": test_template,
            "status": "COMPILED",
            "bytes_count": len(source_code)
        }

        return skill_package
