import pytest
import sqlite3
from solomon_mnemosyne_db import SolomonMnemosyneDB
from solomon_knowledge_graph import KnowledgeGraph

@pytest.fixture
def db():
    # Use an in-memory DB for tests, but we need a file path for SolomonMnemosyneDB
    db_instance = SolomonMnemosyneDB("test_knowledge_graph.db")
    # Clean up DB before run
    conn = sqlite3.connect("test_knowledge_graph.db")
    conn.execute("DELETE FROM card_links")
    conn.execute("DELETE FROM knowledge_cards")
    conn.commit()
    conn.close()

    yield db_instance

def test_knowledge_graph_reasoning(db):
    graph = KnowledgeGraph(db)

    # Insert cards
    db.upsert_card("CARD-A", "Task", "Task A", "Does A")
    db.upsert_card("CARD-B", "Task", "Task B", "Does B")
    db.upsert_card("CARD-C", "Task", "Task C", "Does C")
    db.upsert_card("CARD-D", "Task", "Task D", "Does D")
    db.upsert_card("CARD-E", "Task", "Task E", "Does E")
    db.upsert_card("CARD-F", "Task", "Task F", "Does F")

    # Setup relationships
    # C depends on A
    db.add_link("CARD-C", "CARD-A", "DEPENDS_ON")
    # C uses B
    db.add_link("CARD-C", "CARD-B", "USES")
    # D replaces C
    db.add_link("CARD-D", "CARD-C", "REPLACES")
    # D conflicts with E
    db.add_link("CARD-D", "CARD-E", "CONFLICTS_WITH")
    # D generated by F
    db.add_link("CARD-D", "CARD-F", "GENERATED_BY")

    # Reason over CARD-C
    # Since D REPLACES C, the reasoning should automatically follow to D
    context = graph.reason_over_relationships("CARD-C")

    assert context["active_version"] == "CARD-D"
    assert context["target_card"]["card_id"] == "CARD-D"

    # Now check relationships of D
    assert len(context["replaces"]) == 1
    assert context["replaces"][0]["card_id"] == "CARD-C"

    assert len(context["conflicts_with"]) == 1
    assert context["conflicts_with"][0]["card_id"] == "CARD-E"

    assert len(context["generated_by"]) == 1
    assert context["generated_by"][0]["card_id"] == "CARD-F"

    # Test topology
    topo = graph.resolve_topology()
    # A should be before C
    assert topo.index("CARD-A") < topo.index("CARD-C")

def test_knowledge_graph_formatting(db):
    graph = KnowledgeGraph(db)

    db.upsert_card("CARD-A", "Task", "Task A", "Does A")
    db.upsert_card("CARD-B", "Task", "Task B", "Does B")

    db.add_link("CARD-A", "CARD-B", "DEPENDS_ON")

    context = graph.reason_over_relationships("CARD-A")
    formatted = graph.format_reasoning_for_llm(context)

    assert "--- KNOWLEDGE GRAPH REASONING CONTEXT ---" in formatted
    assert "DEPENDENCIES (Must be resolved first):" in formatted
    assert "[CARD-B]" in formatted
